### ISSUE TITLE
New code not showing up?

### ISSUE THREAD

**Issue by rschmukler** [awetzel/elixir.nvim#8]
It seems that code that I write in my own modules doesn't show up in the omni-complete suggestions. Eventually, after restarting vim (sometimes) the code does show up.

I'm brand new to elixir, so it's possible that I am doing something very stupid and this isn't a bug at all.

**Comment by awetzel** [comment]
The autocompletion is on compiled modules (in _build directory), and only when the modules are loaded.
When you start vim all the modules in _build directory are loaded asynchronously (because if we wait that all your modules and deps are loaded at startup, Vim startup would be veeery slow :) ).

You can call `:ElixirQuickBuild` to build the modules in current file to get autocompletion on it without `mix compile`.
You can set  `g:elixir_autobuild` to call the `ElixirQuickBuild` command automatically during editing. (and  `g:elixir_showerror` to show you build error during the  `ElixirQuickBuild`.

**Comment by rschmukler** [comment]
@awetzel thanks for the quick response. I was using neomake to rebuild the code on save but it looks like it wasn't calling mix compile, instead just running the compiler on the file. Calling `:ElixirQuickBuild` works perfectly. Thanks again!
